version: "3.8"

services:
  db:
    image: pgvector/pgvector:0.8.0-pg17-bookworm
    container_name: pg_vector
    environment:
      POSTGRES_DB: cisco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: node_api
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cisco
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  db_data:
